sudo: false
dist: trusty
language: python
python:
  - "2.7"

install:
  # work done at $HOME, installation of conda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - cd chainer-cv
  - conda env create -f environment.yml
  - source activate chainer_cv
  - pip install -e .

script:
  - pwd
  - pip install flake8
  - pip install autopep8
  - pip install mock
  - pip install nosetests
  - flake8 .
  - autopep8 -r . | tee check_autopep8
  - test ! -s check_autopep8
  - nosetests tests
